version: '3.7'

services:
  # Database
  db:
    image: mysql:latest # last known working version is 8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  # Wordpress
  wordpress:
    build: .
    # run container as user
    user: "${UID}:${GID}"
    ports:
      - 9000:9000
    restart: always
    volumes:
      - ./wp:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./wp:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password

volumes:
  db_data: {}
